# Website Metadata
title: The Spectrum Space
description: A safe and empowering space for LGBTQ+ voices and mental health awareness.
keywords: LGBTQ+, LGBTQ+ mental health, queer community, mental health resources, pride support, transgender support, bisexual community, non-binary support, queer mental health, LGBTQ+ safe space, inclusive community, mental wellness LGBTQ+, LGBTQ+ blog, queer identities, gender diversity, LGBTQ+ support network, mental health awareness, LGBTQ+ advocacy, coming out support, LGBTQ+ positivity
image: https://the-spectrum-space.netlify.app/assets/images/site-image.jpg
author: Blake Sirius Anacleto
og-author: https://www.facebook.com/SoftwareEngineerBlake/
x-creator: "@TheSiriusSystem"

# Website Branding
favicon: /assets/images/favicon.png
logo: /assets/images/logo.png

# Post URL Structure
permalink: /news/:title

collections:
  resources:
    output: true
    permalink: /resources/:title

# Homepage Settings
tagline: Where Every Identity Finds Community
hero-graphic: /assets/images/undraw_loving-story_k8gb.svg
featured-resource: The Trevor Project
featured-resource-logo: /assets/images/the-trevor-project-logo.png
featured-resource-description: 24/7 crisis intervention and suicide prevention services for LGBTQ+ young people under 25.
featured-resource-hotline-text: "Call: 1-866-488-7386"
featured-resource-url: https://www.thetrevorproject.org
featured-resource-hotline-url: tel:+18664887386

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md